<?php

namespace Email\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmailLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailLogRepository extends EntityRepository
{
}
