<?php

namespace Email\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmailTemplateSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailTemplateSectionRepository extends EntityRepository
{
    public function getSectionsNameIndexdById() 
    {
        $dql = "SELECT e FROM \Email\Entity\EmailTemplateSection e";
        
        $sections = $this->getEntityManager()
            ->createQuery($dql)
            ->getResult()
        ;

        $sectionNames = array();
        foreach ($sections as $section) {
            $sectionNames[$section->getId()] = $section->__toString();
        }

        return $sectionNames;

    }
}
