<?php
/**
 * @package License\Entity
 * @author Matt Johnston
 * @author Sean Yao
 * @author Andreas Gerhards <andreas@lero9.co.nz>
 * @copyright Copyright (c) 2014 LERO9 Ltd.
 * @license http://opensource.org/licenses/BSD-3-Clause BSD-3-Clause - Please view LICENSE.md for more information
 */

namespace License\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LicenseAbilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicenseAbilityRepository extends EntityRepository
{
}
