<?php

namespace License\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LicenseCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicenseCodeRepository extends EntityRepository
{
}
