<?php

namespace License\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LicenseKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicenseKeyRepository extends EntityRepository
{
}
