<?php

namespace Magelink\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Andreas Gerhards <andreas@lero9.co.nz>
 */

class ConfigRepository extends EntityRepository
{

    /**
     * Get value by key prefix
     * @param  string $keyPrefix
     * @return array
     */
    public function getValueByKeyPrefix($keyPrefix)
    {
        $dql = "SELECT value FROM \Magelink\Entity\Config AS c"
            ." WHERE c.`key` LIKE :keyPrefix ";

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter('keyPrefix', $keyPrefix.'%')
            ->getResult();
    }

    /**
     * Get value by key
     * @param  string $configKey
     * @return string
     */
    public function getValueByKey($configKey)
    {
        $dql = "SELECT value FROM \Magelink\Entity\Config AS c"
            ." WHERE c.`key` = :configKey ";

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameters(compact('configKey'))
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }

    /**
     * Set value by key
     * @param  string $configKey
     * @param  string $configValue
     * @return mixed
     */
    public function setValueByKey($configKey, $configValue)
    {
        $dql = "UPDATE \Magelink\Entity\Config AS c"
            ." SET c.key = :configValue"
            ." WHERE c.key = :configKey";

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameters(compact('configKey', 'configValue'))
            ->getSingleScalarResult();
    }

}
