<?php
/**
 * @package Magelink\Repository
 * @author Sean Yao
 * @author Andreas Gerhards <andreas@lero9.co.nz>
 * @copyright Copyright (c) 2014 LERO9 Ltd.
 * @license http://opensource.org/licenses/BSD-3-Clause BSD-3-Clause - Please view LICENSE.md for more information
 */

namespace Magelink\Repository;

use Doctrine\ORM\EntityRepository;
use Magelink\Entity\UserRole;

/**
 * UserRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRoleRepository extends EntityRepository
{   
    /**
     * Get the roles assignable to a user
     * @param  array  $excludeIds 
     * @return Doctrine\Common\Collections\ArrayCollection
     */
    public function getAssignableRoles($excludeIds = array()) 
    {
        $excludeIds = array_merge(
            array(UserRole::ROLE_GUEST),
            $excludeIds
        );

        return $this->createQueryBuilder('r')
          ->where('r.id NOT IN (:excludeIds)')
          ->setParameter('excludeIds', $excludeIds)
          ->orderBy('r.roleId', 'ASC')
          ->getQuery()
          ->getResult();
    }
}
