<?php

namespace Magelink\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionRepository extends EntityRepository
{
}
