<?php

return array (
    'service_manager'=>array(
        'invokables'=>array(
            'configService'=>'Magelink\Service\ConfigService',
        ),

        'aliases'=>array('zfcuser_doctrine_em'=>'Doctrine\ORM\EntityManager'),

        'factories'=>array(
            'Magelink\Auth\UnauthorizedStrategy'=>function($serviceLocator) {
                $config = $serviceLocator->get('BjyAuthorize\Config');
                return new \Magelink\Auth\UnauthorizedStrategy($config['template']);
            },

            'BjyAuthorize\Guard\Controller'=>function($serviceLocator) {
                $config = $serviceLocator->get('BjyAuthorize\Config');
                return new \Magelink\Auth\ACLGuardController(
                    $config['guards']['BjyAuthorize\Guard\Controller'], $serviceLocator);
            },

            'BjyAuthorize\Guard\Route'=>function($serviceLocator) {
                    $config = $serviceLocator->get('BjyAuthorize\Config');
                    return new \Magelink\Auth\ACLGuardController(
                        $config['guards']['BjyAuthorize\Guard\Route'], $serviceLocator);
            }
        )
    ),

    'doctrine'=>array(
        'driver'=>array(
            'magelink_entities'=>array(
                'class'=>'Doctrine\ORM\Mapping\Driver\AnnotationDriver',
                'cache'=>'array',
                'paths'=>array(__DIR__ . '/../src/Magelink/Entity')
            ),
            'orm_default'=>array(
                'drivers'=>array(
                    'Magelink\Entity'=>'magelink_entities'
                )
            )
        )
    ),

    'magelink_cron'=>array(
/*
        'synchronizer'=>array(
            'class'=>'\Magelink\Cron\Synchronizer',
            'interval'=>30,
            'offset'=>0,
            'lockTime'=>360,
            'overdue'=>TRUE
        ),
        'retrieval'=>array(
            'class'=>'\Magelink\Cron\Retrieval',
            'interval'=>30,
            'offset'=>20,
            'lockTime'=>360,
            'overdue'=>TRUE
        ),
        'update'=>array(
            'class'=>'\Magelink\Cron\Update',
            'interval'=>30,
            'offset'=>15,
            'lockTime'=>360,
            'overdue'=>TRUE
        ),
        'productStock'=>array(
            'class'=>'\Magelink\Cron\ProductStock',
            'interval'=>30,
            'offset'=>0,
            'lockTime'=>360,
            'overdue'=>TRUE
        )
*/
    ),

    'country_iso2_mapping'=>array (
        'AF'=>'Afghanistan',
        'AX'=>'Åland Islands',
        'AL'=>'Albania',
        'DZ'=>'Algeria',
        'AS'=>'American Samoa',
        'AD'=>'Andorra',
        'AO'=>'Angola',
        'AI'=>'Anguilla',
        'AQ'=>'Antarctica',
        'AG'=>'Antigua and Barbuda',
        'AR'=>'Argentina',
        'AM'=>'Armenia',
        'AW'=>'Aruba',
        'AU'=>'Australia',
        'AT'=>'Austria',
        'AZ'=>'Azerbaijan',
        'BS'=>'Bahamas',
        'BH'=>'Bahrain',
        'BD'=>'Bangladesh',
        'BB'=>'Barbados',
        'BY'=>'Belarus',
        'BE'=>'Belgium',
        'BZ'=>'Belize',
        'BJ'=>'Benin',
        'BM'=>'Bermuda',
        'BT'=>'Bhutan',
        'BO'=>'Bolivia',
        'BQ'=>'Bonaire, Sint Eustatius and Saba',
        'BA'=>'Bosnia and Herzegovina',
        'BW'=>'Botswana',
        'BV'=>'Bouvet Island',
        'BR'=>'Brazil',
        'BQ'=>'British Antarctic Territory',
        'IO'=>'British Indian Ocean Territory',
        'BN'=>'Brunei Darussalam',
        'BG'=>'Bulgaria',
        'BF'=>'Burkina Faso',
        'BU'=>'Burma',
        'BI'=>'Burundi',
        'BY'=>'Byelorussian SSR',
        'CV'=>'Cabo Verde',
        'KH'=>'Cambodia',
        'CM'=>'Cameroon',
        'CA'=>'Canada',
        'CT'=>'Canton and Enderbury Islands',
        'KY'=>'Cayman Islands',
        'CF'=>'Central African Republic',
        'TD'=>'Chad',
        'CL'=>'Chile',
        'CN'=>'China',
        'CX'=>'Christmas Island',
        'CC'=>'Cocos (Keeling) Islands',
        'CO'=>'Colombia',
        'KM'=>'Comoros',
        'CG'=>'Congo',
        'CD'=>'Congo (Democratic Republic of the)',
        'CK'=>'Cook Islands',
        'CR'=>'Costa Rica',
        'CI'=>'Côte d\'Ivoire',
        'HR'=>'Croatia',
        'CU'=>'Cuba',
        'CW'=>'Curaçao',
        'CY'=>'Cyprus',
        'CZ'=>'Czech Republic',
        'CS'=>'Czechoslovakia',
        'DY'=>'Dahomey',
        'DK'=>'Denmark',
        'DJ'=>'Djibouti',
        'DM'=>'Dominica',
        'DO'=>'Dominican Republic',
        'NQ'=>'Dronning Maud Land',
        'TP'=>'East Timor',
        'EC'=>'Ecuador',
        'EG'=>'Egypt',
        'SV'=>'El Salvador',
        'GQ'=>'Equatorial Guinea',
        'ER'=>'Eritrea',
        'EE'=>'Estonia',
        'ET'=>'Ethiopia',
        'FK'=>'Falkland Islands [Malvinas]',
        'FO'=>'Faroe Islands',
        'FJ'=>'Fiji',
        'FI'=>'Finland',
        'FR'=>'France',
        'FX'=>'France, Metropolitan',
        'AI'=>'French Afars and Issas',
        'GF'=>'French Guiana',
        'PF'=>'French Polynesia',
        'FQ'=>'French Southern and Antarctic Territories',
        'TF'=>'French Southern Territories',
        'GA'=>'Gabon',
        'GM'=>'Gambia (The)',
        'GE'=>'Georgia',
        'DD'=>'German Democratic Republic',
        'DE'=>'Germany',
        'GH'=>'Ghana',
        'GI'=>'Gibraltar',
        'GE'=>'Gilbert and Ellice Islands',
        'GR'=>'Greece',
        'GL'=>'Greenland',
        'GD'=>'Grenada',
        'GP'=>'Guadeloupe',
        'GU'=>'Guam',
        'GT'=>'Guatemala',
        'GG'=>'Guernsey',
        'GN'=>'Guinea',
        'GW'=>'Guinea-Bissau',
        'GY'=>'Guyana',
        'HT'=>'Haiti',
        'HM'=>'Heard Island and McDonald Islands',
        'VA'=>'Holy See [Vatican City State]',
        'HN'=>'Honduras',
        'HK'=>'Hong Kong',
        'HU'=>'Hungary',
        'IS'=>'Iceland',
        'IN'=>'India',
        'ID'=>'Indonesia',
        'IR'=>'Iran',
        'IQ'=>'Iraq',
        'IE'=>'Ireland',
        'IM'=>'Isle of Man',
        'IL'=>'Israel',
        'IT'=>'Italy',
        'JM'=>'Jamaica',
        'JP'=>'Japan',
        'JE'=>'Jersey',
        'JT'=>'Johnston Island',
        'JO'=>'Jordan',
        'KZ'=>'Kazakhstan',
        'KE'=>'Kenya',
        'KI'=>'Kiribati',
        'KP'=>'Korea (the Democratic People\'s Republic of)',
        'KR'=>'Korea',
        'KW'=>'Kuwait',
        'KG'=>'Kyrgyzstan',
        'LA'=>'Lao People\'s Democratic Republic',
        'LV'=>'Latvia',
        'LB'=>'Lebanon',
        'LS'=>'Lesotho',
        'LR'=>'Liberia',
        'LY'=>'Libya',
        'LI'=>'Liechtenstein',
        'LT'=>'Lithuania',
        'LU'=>'Luxembourg',
        'MO'=>'Macao',
        'MK'=>'Macedonia',
        'MG'=>'Madagascar',
        'MW'=>'Malawi',
        'MY'=>'Malaysia',
        'MV'=>'Maldives',
        'ML'=>'Mali',
        'MT'=>'Malta',
        'MH'=>'Marshall Islands',
        'MQ'=>'Martinique',
        'MR'=>'Mauritania',
        'MU'=>'Mauritius',
        'YT'=>'Mayotte',
        'MX'=>'Mexico',
        'FM'=>'Micronesia (the Federated States of)',
        'MI'=>'Midway Islands',
        'MD'=>'Moldova',
        'MC'=>'Monaco',
        'MN'=>'Mongolia',
        'ME'=>'Montenegro',
        'MS'=>'Montserrat',
        'MA'=>'Morocco',
        'MZ'=>'Mozambique',
        'MM'=>'Myanmar',
        'NA'=>'Namibia',
        'NR'=>'Nauru',
        'NP'=>'Nepal',
        'NL'=>'Netherlands',
        'AN'=>'Netherlands Antilles',
        'NT'=>'Neutral Zone',
        'NC'=>'New Caledonia',
        'NH'=>'New Hebrides',
        'NZ'=>'New Zealand',
        'NI'=>'Nicaragua',
        'NE'=>'Niger',
        'NG'=>'Nigeria',
        'NU'=>'Niue',
        'NF'=>'Norfolk Island',
        'MP'=>'Northern Mariana Islands',
        'NO'=>'Norway',
        'OM'=>'Oman',
        'PC'=>'Pacific Islands (Trust Territory)',
        'PK'=>'Pakistan',
        'PW'=>'Palau',
        'PS'=>'Palestine, State of',
        'PA'=>'Panama',
        'PZ'=>'Panama Canal Zone',
        'PG'=>'Papua New Guinea',
        'PY'=>'Paraguay',
        'PE'=>'Peru',
        'PH'=>'Philippines',
        'PN'=>'Pitcairn',
        'PL'=>'Poland',
        'PT'=>'Portugal',
        'PR'=>'Puerto Rico',
        'QA'=>'Qatar',
        'RE'=>'Réunion',
        'RO'=>'Romania',
        'RU'=>'Russian Federation',
        'RW'=>'Rwanda',
        'BL'=>'Saint Barthélemy',
        'SH'=>'Saint Helena, Ascension and Tristan da Cunha',
        'KN'=>'Saint Kitts and Nevis',
        'LC'=>'Saint Lucia',
        'MF'=>'Saint Martin',
        'PM'=>'Saint Pierre and Miquelon',
        'VC'=>'Saint Vincent and the Grenadines',
        'WS'=>'Samoa',
        'SM'=>'San Marino',
        'ST'=>'Sao Tome and Principe',
        'SA'=>'Saudi Arabia',
        'SN'=>'Senegal',
        'RS'=>'Serbia',
        'CS'=>'Serbia and Montenegro',
        'SC'=>'Seychelles',
        'SL'=>'Sierra Leone',
        'SK'=>'Sikkim',
        'SG'=>'Singapore',
        'SX'=>'Sint Maarten',
        'SK'=>'Slovakia',
        'SI'=>'Slovenia',
        'SB'=>'Solomon Islands',
        'SO'=>'Somalia',
        'ZA'=>'South Africa',
        'GS'=>'South Georgia and the South Sandwich Islands',
        'SS'=>'South Sudan',
        'RH'=>'Southern Rhodesia',
        'ES'=>'Spain',
        'LK'=>'Sri Lanka',
        'SD'=>'Sudan',
        'SR'=>'Suriname',
        'SJ'=>'Svalbard and Jan Mayen',
        'SZ'=>'Swaziland',
        'SE'=>'Sweden',
        'CH'=>'Switzerland',
        'SY'=>'Syrian Arab Republic',
        'TW'=>'Taiwan',
        'TJ'=>'Tajikistan',
        'TZ'=>'Tanzania',
        'TH'=>'Thailand',
        'TL'=>'Timor-Leste',
        'TG'=>'Togo',
        'TK'=>'Tokelau',
        'TO'=>'Tonga',
        'TT'=>'Trinidad and Tobago',
        'TN'=>'Tunisia',
        'TR'=>'Turkey',
        'TM'=>'Turkmenistan',
        'TC'=>'Turks and Caicos Islands',
        'TV'=>'Tuvalu',
        'UG'=>'Uganda',
        'UA'=>'Ukraine',
        'AE'=>'United Arab Emirates',
        'GB'=>'United Kingdom',
        'US'=>'United States',
        'UM'=>'United States Minor Outlying Islands',
        'PU'=>'United States Miscellaneous Pacific Islands',
        'HV'=>'Upper Volta',
        'UY'=>'Uruguay',
        'SU'=>'USSR',
        'UZ'=>'Uzbekistan',
        'VU'=>'Vanuatu',
        'VE'=>'Venezuela',
        'VN'=>'Viet Nam',
        'VD'=>'Viet-Nam, Democratic Republic of',
        'VG'=>'Virgin Islands (British)',
        'VI'=>'Virgin Islands (U.S.)',
        'WK'=>'Wake Island',
        'WF'=>'Wallis and Futuna',
        'EH'=>'Western Sahara*',
        'YE'=>'Yemen',
        'YD'=>'Yemen, Democratic',
        'YU'=>'Yugoslavia',
        'ZR'=>'Zaire',
        'ZM'=>'Zambia',
        'ZW'=>'Zimbabwe'
    )
);

?>
