<div class="extra">

    <div class="extra-inner">

        <div class="container">

            <div class="row">
                    <div class="col-sm-3 col-md-3 col-lg-3">
                        <h4>HOPS Admin</h4>
                        <ul>
                            <li><a href="#none">HOPS HOPS</a></li>
                        </ul>
                    </div>
                    <!-- /span3 -->
                    <div class="col-sm-3 col-md-3 col-lg-3">
                        <h4>Support</h4>
                        <ul>
                            <li><a href="#none">Frequently Asked Questions</a></li>
                        </ul>
                    </div>
                    
                    <!-- /span3 -->
                </div> <!-- /row -->

        </div> <!-- /container -->

    </div> <!-- /extra-inner -->

</div> <!-- /extra -->

    
<div class="footer">
    
    <div class="footer-inner">
        
        <div class="container">
            
            <div class="row">
                
                <div class="col-sm-12 col-md-12 col-lg-12">
                    Copyright &copy; HealthPost <?php echo date('Y')?>. All Rights Reserved.  HOPS Powered by <a href="http://www.lero9.com/">LERO9 Limited</a>.
                </div> <!-- /span12 -->

            </div> <!-- /row -->
            
        </div> <!-- /container -->
        
    </div> <!-- /footer-inner -->
    
</div> <!-- /footer -->