<div class="header-wrap">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                MageLink Web Console
            </a>
        </div>
        <div class="navbar-collapse">
            <?php if ($user = $this->zfcUserIdentity()) : ?>
                <ul class="navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="glyphicon glyphicon-user"></i>
                            <?php echo $user->getDisplayName() ?>
                            <b class="caret"></b>
                        </a>

                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url('zfcuser/logout') ?>">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            <?php endif ?>
        </div>
    </div>
</div>

<?php if ($this->zfcUserIdentity()) : ?>
    <div class="subnavbar">
        <div class="subnavbar-inner">
            <div class="container">
                <?php
                    echo $this->navigation('navigation')
                        ->menu()
                        ->setPartial('layout/headerMenu')
                ?>
            </div> <!-- /container -->
        </div> <!-- /subnavbar-inner -->
    </div> <!-- /subnavbar -->
<?php endif ?>




