<?php

namespace Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EntityActionDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityActionDataRepository extends EntityRepository
{
}
