<?php

namespace Log\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuditLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuditLogRepository extends EntityRepository
{
}
