<?php

namespace Report\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReportDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportDataRepository extends EntityRepository
{
}
