<?php
/**
 * @package Node\Repository
 * @author Sean Yao
 * @copyright Copyright (c) 2014 LERO9 Ltd.
 * @license http://opensource.org/licenses/BSD-3-Clause BSD-3-Clause - Please view LICENSE.md for more information
 */

namespace Node\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NodeDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeDataRepository extends EntityRepository
{
}
