<?php
/**
 * @package Node\Repository
 * @author Sean Yao
 * @copyright Copyright (c) 2014 LERO9 Ltd.
 * @license http://opensource.org/licenses/BSD-3-Clause BSD-3-Clause - Please view LICENSE.md for more information
 */

namespace Node\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NodeStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeStatusRepository extends EntityRepository
{

    /**
     * @param $node_id
     * @param $entity_type
     * @param $action
     * @return \Node\Entity\NodeStatus
     */
    public function getStatusForNode($node_id, $entity_type_id, $action)
    {
        $dql = "SELECT n FROM \Node\Entity\NodeStatus n WHERE n.node = :node_id AND n.entityTypeId = :entity_type_id AND n.action = :action";

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter(':node_id', $node_id)
            ->setParameter(':entity_type_id', $entity_type_id)
            ->setParameter(':action', $action)
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }

}
