<?php

namespace Node\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NodeDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeDataRepository extends EntityRepository
{
}
