<?php

namespace Node\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeRepository extends EntityRepository
{

    public function getActiveNodes()
    {
        $dql = "SELECT n FROM \Node\Entity\Node n ";

        return $this->getEntityManager()
            ->createQuery($dql)
            ->getResult();
    }

    public function getActiveNodesByType($type_str)
    {
        $dql = "SELECT n FROM \Node\Entity\Node n WHERE n.type = :type";

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter('type', $type_str)
            ->getResult();
    }

    /**
     * Get one HOPS node
     * @return Node\Entity\Node
     */
    public function getOneHOPSNode()
    {
        $dql = "SELECT n FROM \Node\Entity\Node n WHERE n.type = :type";

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter('type', 'HOPS')
            ->setMaxResults(1)
            ->getOneOrNullResult()
        ;
    }

}
