<?php

namespace Router\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RouterStatEdgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouterStatEdgeRepository extends EntityRepository
{
}
