<?php

namespace Router\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RouterFilterDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouterFilterDataRepository extends EntityRepository
{
}
