<?php

namespace Router\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RouterEdgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouterEdgeRepository extends EntityRepository
{

    public function getAssignedEdges($from_node_id, $entity_type_id, $type){
        $dql = "SELECT re FROM \Router\Entity\RouterEdge re WHERE re.nodeFrom = :from_node_id AND re.entityTypeId = :entity_type_id";
        switch($type){
            case \Entity\Update::TYPE_CREATE:
                $dql .= ' AND re.enableCreate = 1';
                break;
            case \Entity\Update::TYPE_UPDATE:
                $dql .= ' AND re.enableUpdate = 1';
                break;
            case \Entity\Update::TYPE_DELETE:
                $dql .= ' AND re.enableDelete = 1';
                break;
            case \Entity\Update::TYPE_ACTION:
                $dql .= ' AND re.enableAction = 1';
                break;
            default:
                throw new \Magelink\Exception\MagelinkException('Invalid update/action type: ' . $type);
        }

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter(':from_node_id', $from_node_id)
            ->setParameter(':entity_type_id', $entity_type_id)
            ->getResult();
    }

}
