<?php

namespace Router\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RouterStatTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouterStatTypeRepository extends EntityRepository
{
}
