<?php $this->headLink()->appendStylesheet($this->basePath() . '/css/pages/signin.css') ?>

<div class="account-container">
    <?php if ($errorMessage) : ?>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <?php echo $this->escapeHtml($errorMessage)?>
        </div>
    <?php endif ?>

    <div class="content clearfix jsLoginForm" >

        <form action="#" method="post">
        
            <h1>Password Reset</h1>       
            <?php if ($user) :?>
                <div class="login-fields">
                    
                    <p>Please enter new password</p>
                    
                    <div class="field">
                        <label for="pasword">Password:</label>
                        <input type="password" name="password" value="" placeholder="Password" class="login password-field">
                    </div> <!-- /field -->
                    
                    <div class="field">
                        <label for="paswordRetype">Retype Password:</label>
                        <input type="password"  name="passwordRetype" value="" placeholder="Retype Password" class="login password-field">
                    </div> <!-- /password -->
                    
                </div> <!-- /login-fields -->


                <div class="login-actions">
                                        
                    <button class="button btn btn-success btn-large">Submit</button>
                    
                </div> <!-- .actions -->
            <?php endif ?>   
        </form>
        
    </div> 

</div>